version: "2.2"
services:
  7dtd:
    build:
      context: ./
      dockerfile: Dockerfile
    cpu_count: 1
    cpus: 0.5
    mem_limit: 2G
    volumes:
      - ./config:/configs
    ports:
      - "29600:26900/tcp"
      - "29600:26900/udp"
      - "26901:26901/udp"
      - "26902:26902/udp"

    command: sh -c "cp /configs/startserver.sh ./startserver.sh && cp /configs/serverconfig.xml ./serverconfig.xml && /opt/7d2d/startserver.sh -configfile=serverconfig.xml"
